Perform all updates in one request
house-of-abbey/GarminHomeAssistant pull request #173
Opened 2024-08-26 19:12 UTC by JosephAbbey

2024-08-27 19:51 UTC, philipabbey commented
I think we need to amend the default polling delay now that we perform a single large status update. If we don't force a change, we'll have rapid fire API calls which will wear down device batteries.

1. Can we set a new default in the properties?
2. Would 5 seconds be reasonable default delay?
3. Can we force the new default on devices when they install the update in order to prevent nasty surprises?
   - Perhaps change the name of the Property field so that it looks like a new one?

2024-08-27 19:54 UTC, philipabbey commented
`propoerties.xml`:

```
<property id="poll_delay_combined" type="number">5</property>
```

2024-08-27 20:01 UTC, philipabbey requested changes

2024-08-27 20:01 UTC, philipabbey commented on compile_sim.cmd
Can we back the changes out of this file? they look specific to your local installation.

2024-08-27 20:01 UTC, philipabbey commented on source/HomeAssistantTapMenuItem.mc
> +    }
Is this not redundant and therefore deletable?

2024-08-27 20:01 UTC, philipabbey commented on source/HomeAssistantTapMenuItem.mc
> +
Why do we need this?

2024-08-27 20:01 UTC, philipabbey commented on source/HomeAssistantTapMenuItem.mc
> +    }
Ah, is this about uniformity?

2024-08-27 20:01 UTC, philipabbey commented on source/HomeAssistantTapMenuItem.mc
> +
Ah, is this about uniformity?

2024-08-27 21:38 UTC, JosephAbbey commented on source/HomeAssistantTapMenuItem.mc
> +    }
The standard is that every menu item has a `buildTemplate` and `updateState` function (there would be an interface if monkey c had those).

2024-08-28 07:54 UTC, JosephAbbey commented
> * Perhaps change the name of the Property field so that it looks like a new one?

We need to write a new name and run translation

2024-08-28 18:41 UTC, philipabbey commented
`settings.xml`:

```
  <setting
    propertyKey="@Properties.poll_delay_combined"
    title="@Strings.SettingsPollDelay"
  >
    <settingConfig type="numeric" min="0" />
  </setting>
```

We might need to insist on a minimum here.

2024-08-29 19:55 UTC, philipabbey commented
On testing we decided:

- 5s default polling delay
- 0s minimum polling delay

No further code chages.

2024-08-29 19:55 UTC, philipabbey approved these changes

2024-08-29 19:55 UTC, merged