Initial version with "auto quit"
house-of-abbey/GarminHomeAssistant pull request #24
Opened 2023-12-02 19:08 UTC by philipabbey

Quit the application after a user settable period of time based on a timeout value from the settings.

@Someone0nEarth is this non-glance app of any interest to you?

2023-12-04 12:07 UTC, Someone0nEarth commented
Hi!

This would prevent the battery drain issue. 👍

But on the UX level, having a widget/glance is much more comfy for me: Only to swipe down or up for starting. As an app, I would have to press a button on the watch (using my thumb and one finger) and then selecting the app for starting.

2023-12-04 13:20 UTC, philipabbey commented
I think we can have both.

- Testing has shown the widget still gives me what I want, a standard application, and what you want.
- We then add the auto quit so the app also exits.
   - This should either live along side the auto close of the widget, or be disabled (timeout=0).
 
Perhaps this combination gives us the best of all worlds?

2023-12-04 13:36 UTC, Someone0nEarth commented
That should work for me.

So, we add the timer you implemented and also change the type from "watch-app" to "widget" in the manifest.xml .

There is one "ugly" thing left in my dirt & quick widget/glance hack: When the user swipes back for quitting the widget, in the end, there will be a unnecessary "black screen" to swipe off. This is a circumstance of how this application views are currently implemented. I will try to change this later today or tomorrow and then we can see, if we will like it and go further to change the app to widget type.

2023-12-05 20:23 UTC, philipabbey commented
Suggest we close this one off as an interim solution that should be compatible (or at least tolerable) with the widget proposal from @Someone0nEarth.

2023-12-05 21:18 UTC, JosephAbbey requested changes

2023-12-05 21:18 UTC, JosephAbbey commented on resources/settings/settings.xml
> +<!--
It is probably not the best idea to leave stale code that does not work commented out.

2023-12-06 22:07 UTC, philipabbey commented on resources/settings/settings.xml
> +<!--
Done

2023-12-06 22:35 UTC, JosephAbbey approved these changes

2023-12-06 22:43 UTC, merged