Change type to widget with glance view support
house-of-abbey/GarminHomeAssistant pull request #30
Opened 2023-12-16 16:52 UTC by Someone0nEarth

2023-12-16 17:25 UTC, JosephAbbey requested changes
Just minor tweeks, this is looking good!

2023-12-16 17:25 UTC, JosephAbbey commented on source/HomeAssistantGlanceView.mc
> +// Application root for GarminHomeAssistant
Should be "Glance view for GarminHomeAssistant" or something.

2023-12-16 17:25 UTC, JosephAbbey commented on source/RootView.mc
> +        var bg = 0x3B444C;
Is it possible to replace this with `Graphics.COLOR_BLUE` for readability?
Is this a specific blue for a reason?

2023-12-16 17:29 UTC, philipabbey requested changes
Looking good 🕺.

2023-12-16 17:29 UTC, philipabbey commented on source/HomeAssistantGlanceView.mc
> +        var text = "GarminHomeAssistant";
How about we fetch the application name from the string resource file?
`WatchUi.loadResource($.Rez.Strings.AppName)`

2023-12-16 18:49 UTC, Someone0nEarth commented on source/RootView.mc
> +        var bg = 0x3B444C;
> Is it possible to replace this with `Graphics.COLOR_BLUE` for readability? Is this a specific blue for a reason?

Copy pasta bg color from ErrorView. Was thinking to move this color to Globals.mc (but forgot it :)

2023-12-16 18:58 UTC, philipabbey commented on source/RootView.mc
> +        var bg = 0x3B444C;
I think that was my fault. I originally just copied the ErrorView.mc from another application. Would you mind sticking `Graphics.COLOR_BLUE` in to fix that legacy code please?

2023-12-16 20:52 UTC, Someone0nEarth commented on source/HomeAssistantGlanceView.mc
> +        var text = "GarminHomeAssistant";
https://github.com/house-of-abbey/GarminHomeAssistant/commit/e6d5053ebba4b2fa1d30ccadf7e549b96ea05ad4

2023-12-16 21:01 UTC, JosephAbbey commented on source/RootView.mc
> +        var bg = 0x3B444C;
In fact, it may be better to use black here to be less jarring.

2023-12-16 21:04 UTC, Someone0nEarth commented on source/RootView.mc
> +        var bg = 0x3B444C;
https://github.com/house-of-abbey/GarminHomeAssistant/commit/ba5f90c682734b2570e8622c68a58a90919780ec

Change ErrorView to blue and RootView to black (error views should have their "own" color for better differentiating)

2023-12-16 21:04 UTC, merged

2023-12-16 21:05 UTC, JosephAbbey commented
Nice work!

2023-12-16 21:11 UTC, Someone0nEarth commented
Oh, there is still the widget uuid in the manifest.. should be change back to the original watch-app uuid in `main`, I guess

https://github.com/house-of-abbey/GarminHomeAssistant/blob/e3a6da4c9f1566ba5068166783f55bf45da7cbe1/manifest.xml

2023-12-17 08:10 UTC, philipabbey commented
Don't worry about the App ID in the manifest, we just keep changing it to match the test/live deployment route. Your private App ID will just be another in the comments for swapping in.