52 allow parameters to be send with tap menu items
house-of-abbey/GarminHomeAssistant pull request #82
Opened 2024-01-18 21:17 UTC by philipabbey

Calling for review. Just testing the effect of removing `ErrorView.unShow()` from callbacks on actual devices.

2024-01-18 21:27 UTC, JosephAbbey requested changes

2024-01-18 21:27 UTC, JosephAbbey commented on source/HomeAssistantView.mc
> +                data    = tap_action.get("data");    // Optional
Should these have type annotations like the ones above?

2024-01-18 21:27 UTC, JosephAbbey commented on source/HomeAssistantMenuItem.mc
> +        }
Do we have plans to conditionally include this to allow for services like notify that complain?

Should we be using `entity_id` as the identifier? If we use something else, `entity_id` can be optional which would solve this (especially as it isn't actually used for `TemplateMenuItem`).

2024-01-19 09:47 UTC, philipabbey commented on source/HomeAssistantMenuItem.mc
> +        }
So our previous discussion considered how we many exceptions to including `entity_id`, and we left it as, keep it simple, no exceptions. But we do have the opportunity, and we could make the `mIdentifier` a simple one-up number so that multiple menu items can use the same `entity_id`.

How many exceptions do we need? Since they have to be hard coded.

2024-01-19 09:50 UTC, philipabbey commented on source/HomeAssistantView.mc
> +                data    = tap_action.get("data");    // Optional
```
            var service    = items[i].get("service")    as Lang.String     or Null; // Deprecated schema
            var confirm    = false                      as Lang.Boolean    or Null;
            var data       = null                       as Lang.Dictionary or Null;
```

> the ones above?

...are type definitions. Because they provide the type of the variable on the left hand side of these assignments, the "as Lang.*" in the assignment is already covered and becomes unnecessary surely?

2024-01-19 14:46 UTC, philipabbey commented on source/HomeAssistantMenuItem.mc
> +        }
@JosephAbbey > Should we be using entity_id as the identifier?
@philipabbey > we could make the mIdentifier a simple one-up number

The `HomeAssistantToggleMenuItem` continues to use `mIdentifier` in the `makeWebRequest()` call. Those object instances presently do not include any additional `data` field for parameters to populate with the current value of `mIdentifier`. So we would end up making an inconsistent change if performed this change for `toggle`, `template` and `tap`, or we need to add more code and a member variable to `HomeAssistantToggleMenuItem`, which bloats the code.

2024-01-19 18:15 UTC, JosephAbbey approved these changes

2024-01-19 18:15 UTC, merged